apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data-storage-class
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true